apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:vs85R7QfZQgZfQrOqW4veTTZpqp+X9cnNLyoBvh+tK6KvDWpC3mFsPM2X8RoUbkh,iv:OOU9hy+7i3qdxhI2JgcE5eL1VY320sFpANgl6GxyUiM=,tag:y9mM27aHk6Snz/Q+Mq7GTQ==,type:str]
    #ENC[AES256_GCM,data:c93zwgbknDygW2hS8ChoTn8gOPY+GX1aYWDDa9ASAdoMwMBJ61QDN3aEu2yyZoQesn+6bYLlJUCdD7RVl6u03umSiAcgx4gAHZgdrHVJtZk=,iv:rQWBAm4X6A6pUM+FoQG2GzD1imdTnXD6y7xuIrEuePk=,tag:mFpmea1DrVZmcdkIc/l08A==,type:comment]
    #ENC[AES256_GCM,data:CV/KtDdMkJ4QAMvSJkbzD8lunYcxRoNbhX0nKJ4E/C96Az15l6j6Micmou9CdTGqDR01+NlpOcqS,iv:q0Wa/arkcPs1rCuSqye/75TDV/OuUAqs+LoA/SAG68A=,tag:n9HX38IayCIFAe5MIkeElg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY1loSk9vbUpoTURsTm52
            ODdVc2dHK3dhNXRKd3JHelhSUFBRVXRHb0Y0CldJTHA5Z2E4Vk9HaEJxTnNTZ3R2
            NUJZaXFwSExrMW5JaWwveEZOT1NSRmcKLS0tIFh0TFI1MnhPbk11eEdhWkxQQkNy
            VFNkUlhYUllleC9QY0hHT3JwMGVWazQK7PWzSDr7D/3pprqs9f7CiZFm1TPbuWcZ
            9S3A5aljhhnPA91dJiHWqMnYJOHM3TrNXrtCATskGn5kE0FRGqWHzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15urfxejx6j728rte72xac2wa2jll9k246a03lpyw8ruxsg3a3ahqsr59ax
    encrypted_regex: ^(data)$
    lastmodified: "2026-09-09T15:28:07Z"
    mac: ENC[AES256_GCM,data:03nCtQxePoTeE/EuLNVvC4TDB4MF+eBU6UltQO62mhlsBpn526UeswwIrNB8mxklD7b0n+MT3ashx7uL0mKcQAyEirRCisigifypwyWt1nbFAD8PHvx3yB2xGkbYMc/XL/MeBTw1ab4latCUI71ZdLeXjF73LvJK071puSA8zII=,iv:nLltPqF5Tywth74QLSWP7tFK5KOzosEuaVC0bpDkW+I=,tag:FpXkPdB/lxEMtuTVThnaUw==,type:str]
    version: 3.13.3
