apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pong-o-svc
spec:
  type: ClusterIP
  selector:
    app: pong-o
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3000