apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: string-reader
          image: levonml/1.10-reader:latest
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
        - name: string-writer
          image: levonml/1.10-writer:latest
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files